import { NextRequest, NextResponse } from "next/server"
import { auth } from "@clerk/nextjs/server"
import { clerkClient } from "@clerk/nextjs/server"
import { neon } from "@neondatabase/serverless"
import { slugifyName } from "@/lib/usernames"

function getDb() {
  return neon(process.env.DATABASE_URL!)
}

/**
 * Admin-only migration endpoint: backfill existing auto-generated usernames
 * with Clerk's native usernames where available.
 *
 * Only updates rows where is_custom = FALSE (auto-generated).
 * Requires ADMIN_MIGRATION_SECRET in Authorization header.
 *
 * Usage: POST /api/admin/migrate-usernames with header:
 *   Authorization: Bearer <ADMIN_MIGRATION_SECRET>
 */
export async function POST(req: NextRequest) {
  const secret = req.headers.get("authorization")?.replace("Bearer ", "")
  if (secret !== process.env.ADMIN_MIGRATION_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
  }

  try {
    const sql = getDb()
    const client = await clerkClient()

    // Get all non-custom usernames (auto-generated)
    const autoGenerated = await sql`
      SELECT user_id, username FROM usernames WHERE is_custom = FALSE
    `

    let updated = 0
    let errors = 0

    for (const row of autoGenerated) {
      try {
        const userId = row.user_id as string
        const currentUsername = row.username as string

        // Fetch from Clerk
        const clerkUser = await client.users.getUser(userId)
        const clerkUsername = clerkUser.username

        if (!clerkUsername) continue // Clerk user has no username set, skip

        const slugged = slugifyName(clerkUsername)
        if (slugged === currentUsername) continue // Already matches, skip

        // Update our DB
        await sql`
          UPDATE usernames
          SET username = ${slugged}
          WHERE user_id = ${userId}
        `
        updated++
      } catch (e) {
        console.error(`[v0] Migration error for user ${row.user_id}:`, e)
        errors++
      }
    }

    return NextResponse.json({
      message: "Migration complete",
      totalAutoGenerated: autoGenerated.length,
      updated,
      errors,
    })
  } catch (err: any) {
    console.error("[v0] Migration failed:", err)
    return NextResponse.json(
      { error: err.message || "Migration failed" },
      { status: 500 },
    )
  }
}
